$ErrorActionPreference = "Stop"

$reportPath = "WINDOWS_SMOKETEST_RUN.md"
$sha = if ($env:GITHUB_SHA) { $env:GITHUB_SHA } else { "unknown" }
$server = if ($env:GITHUB_SERVER_URL) { $env:GITHUB_SERVER_URL } else { "https://github.com" }
$repo = if ($env:GITHUB_REPOSITORY) { $env:GITHUB_REPOSITORY } else { "unknown/unknown" }
$runId = if ($env:GITHUB_RUN_ID) { $env:GITHUB_RUN_ID } else { "0" }
$runUrl = "$server/$repo/actions/runs/$runId"

@"
# Windows Smoke-Test Report (Auto-generated by CI)

## Run metadata
- Commit SHA: `$sha`
- Workflow run URL: $runUrl
- Artifact: `offline-pdf-reader-windows-portable`

## CI checks (this run)
- ✅ Validation checks passed (`validate_helpers.py`, `validate_parser_regression.py`)
- ✅ Windows smoke checks passed (EXE + bundled Tesseract + ZIP)
- ✅ Artifact summary present

## Manual 5-point smoke test (to complete on Windows)
1. Start
   - [ ] App starts without error
   - Notes:
2. Viewer
   - [ ] Page navigation + zoom + search hit jump works
   - Notes:
3. OCR
   - [ ] Multi-page OCR run completed with progress + result dialog
   - Notes:
4. Rename
   - [ ] Batch-rename preview shows Status/Confidence/Source/Reason
   - [ ] Dry-run cancel + confirm path verified
   - Notes:
5. Export
   - [ ] TXT/JSON/CSV export generated
   - Notes:

## Result
- Overall: [ ] PASS / [ ] FAIL
- Blocking issues:
- Follow-up actions:
"@ | Out-File -FilePath $reportPath -Encoding utf8

Write-Host "Generated $reportPath"
